# Generated by Django 4.1.7 on 2023-03-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradename', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TimeField()),
                ('status', models.CharField(choices=[('добавлен', 'добавлен'), ('готовится', 'готовится'), ('готов', 'готов'), ('отменен', 'отменен'), ('оплачен', 'оплачен')], max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('fathername', models.CharField(max_length=200)),
                ('login', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tortotoro.grades')),
            ],
        ),
    ]
